# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a1527d2e4f753ac4e88383c022bd27e3ece1b23aed6d8133026ec41a87ff4fe6a620756c5cf0170850c836f7514bd2f1b13969e553248f8eced6f7318a35e22

test:
  secret_key_base: d7451bf079e2daeb198085aef24de092bb48e0e898090cbfba5ab007f0188dd5ac094f0462e8530bae4b4d049c41c1f81c28b4096c8d0bc7a755d8745bb0f915

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
